name: 编译上传文件

on:
  push:
    branches: [ main ]
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
           go build
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet xdd
